import os

KIWI_API_KEY = os.getenv("KIWI_API_KEY")
KIWI_API_ENDPOINT = os.getenv("KIWI_API_ENDPOINT")
SHEETY_ENDPOINT = os.getenv("SHEETY_ENDPOINT")
SHEETY_API_KEY = os.getenv("SHEETY_API_KEY")
SHEET_LINK = os.getenv("SHEET_LINK")
MAIL_GUN_ENDPOINT = os.getenv("MAIL_GUN_ENDPOINT")
MAIL_GUN_API_KEY = os.getenv("MAIL_GUN_API_KEY")
MAIL_RECEIVER = os.getenv("MAIL_RECEIVER")
MAIL_SENDER = os.getenv("MAIL_SENDER")
